### ISSUE TITLE
'lux new' fails on Windows

### ISSUE THREAD

**Issue by bjwyse** [postlight/lux#143]
Did 'npm install -g' but 'lux new' fails with the following error:

```
~/projects/ember $ lux new lux-test
c:\Users\xxxx\AppData\Roaming\npm\node_modules\lux-framework\dist\cli.js:198
    let rescue = arguments.length <= 1 || arguments[1] === undefined ? K : arguments[1];
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (c:\Users\bwyse\AppData\Roaming\npm\node_modules\lux-framework\bin\lux:9:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
~/projects/ember $ npm -v
3.6.0
~/projects/ember $ node -v
v5.6.0
~/projects/ember $
```

**Comment by bjwyse** [comment]
Updated NodeJS to latest v6.2.1 and it worked.
