### ISSUE TITLE
Cannot find module '../appindex.js'

### ISSUE THREAD

**Issue by bjwyse** [postlight/lux#144]
Followed instructions from: https://github.com/postlight/lux/wiki/Getting-Started

After creating a new app, 'lux serve' fails:

```
~/projects/ember/lux-test-2 (master) $ lux serve
Error: Cannot find module '../appindex.js' from 'c:/Users/xxxxx/projects/ember/lux-test-2/dist'
    at C:\Users\xxxx\projects\ember\lux-test-2\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\xxxx\projects\ember\lux-test-2\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\xxxx\projects\ember\lux-test-2\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\xxxx\projects\ember\lux-test-2\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
~/projects/ember/lux-test-2 (master) $
```

**Comment by zacharygolba** [comment]
😞  Currently we do not support Windows. This is most likely an issue with Windows paths using `\` and UNIX based systems using `/`. I'm going to close this issue and open up a new one to add Windows support.

😄  Thanks for bringing this up!
