### ISSUE TITLE
Passing Invalid JSON to a POST/PATCH request crashes

### ISSUE THREAD

**Issue by kev5873** [postlight/lux#218]
Passing invalid JSON to a POST/PATCH requests crashes lux, and generates no response.

```
/Users/kevin/Documents/lux-todo/node_modules/lux-framework/src/packages/server/utils/body-parser.js:13
      JSON.parse(body) : parseQueryString(body);
           ^
SyntaxError: Unexpected token ; in JSON at position 96
    at Object.parse (native)
    at IncomingMessage.onEnd (/Users/kevin/Documents/lux-todo/node_modules/lux-framework/src/packages/server/utils/body-parser.js:13:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Creating this issue just to document it.

**Comment by zacharygolba** [comment]
Closed by #229.
