### ISSUE TITLE
Config Template is Missing Quotes Around `logging.level` and `logging.format` Values

### ISSUE THREAD

**Issue by zacharygolba** [postlight/lux#254]
The [config template](https://github.com/postlight/lux/blob/master/src/packages/cli/templates/config.js) is missing wrapping quotes for the following values:

* logging.level
* logging.format

--

When attempting to build a newly bootstrapped project created with the `lux new` command the following error thrown.

```
ReferenceError: DEBUG is not defined
    at Object.<anonymous> (/Users/zacharygolba/Desktop/blog/config/environments/development.js:3:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at loader (/Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/packages/loader/index.js:17:22)
    at /Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/packages/cli/commands/dbcreate.js:18:7
    at next (native)
    at step (/Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/utils/k.js:13:3)
    at /Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/utils/k.js:13:3
    at /Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/utils/k.js:13:3
    at dbcreate (/Users/zacharygolba/Desktop/blog/node_modules/lux-framework/src/packages/cli/commands/dbcreate.js:9:1)
    at exec (/Users/zacharygolba/.nvm/versions/node/v6.3.1/lib/node_modules/lux-framework/bin/lux:56:18)
```

**Comment by zacharygolba** [comment]
Closed by #260
