### ISSUE TITLE
Bug: Seeding db in social-network example fails when driver is postgres

### ISSUE THREAD

**Issue by adampash** [postlight/lux#306]
I haven't looked into this yet but it looks like the beforeSave hook that generates the salted password isn't working as expected.

The error looks like:

```
{ error: insert into "users" ("created_at", "email", "name", "password", "password_salt", "updated_at") values ($1, $2, $3, $4, $5, $6) returning "id" - null value in column "password_salt" violates not-null constraint
    at Connection.parseE (/Users/ap/code/postlight/internal/lux/examples/social-network/node_modules/pg/lib/connection.js:551:11)
    at Connection.parseMessage (/Users/ap/code/postlight/internal/lux/examples/social-network/node_modules/pg/lib/connection.js:378:17)
    at Socket.<anonymous> (/Users/ap/code/postlight/internal/lux/examples/social-network/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
  name: 'error',
  length: 299,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (3, Wellington Cormier, Lyla.Yundt@yahoo.com, feGqIlBVWIu6wBp, null, 2016-08-12 11:47:29.616-04, 2016-08-12 11:47:29.616-04).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'users',
  column: 'password_salt',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1699',
  routine: 'ExecConstraints' }
```

**Comment by zacharygolba** [comment]
Closed by #308
