### ISSUE TITLE
Documentation about defining routes are invalid

### ISSUE THREAD

**Issue by Photon79** [postlight/lux#455]
`app/routes.js`

```
export default (route, resource) => {
  resource('users');
};
```

Error when `lux s`

```
TypeError: resource is not a function
    at Object.routes (/home/photon/projects/lux-test/app/routes.js:1:37)
    at build (/home/photon/projects/lux-test/node_modules/lux-framework/src/packages/router/definitions/index.js:44:13)
    at new Router (/home/photon/projects/lux-test/node_modules/lux-framework/src/packages/router/index.js:20:25)
    at /home/photon/projects/lux-test/node_modules/lux-framework/src/packages/application/initialize.js:85:18
    at next (native)
    at step (/home/photon/projects/lux-test/node_modules/lux-framework/src/utils/set-type.js:22:3)
    at /home/photon/projects/lux-test/node_modules/lux-framework/src/utils/set-type.js:22:3
```

**Comment by gentle-noah** [comment]
This is correct. The place I look when hitting these errors in the example apps. They are in the process of creating better docs for the 1.0 release. I ran into this same issue a few weeks ago.

**Comment by zacharygolba** [comment]
Thanks for jumping on this @gentle-noah!

@Photon79 we currently have two PRs (#418 & #456) that we're hoping to land in this coming week! Until then, check out [this example](https://github.com/postlight/lux/blob/master/examples/social-network/app/routes.js) for a proper `routes.js`.

**Comment by zacharygolba** [comment]
Docs about declaring routes is [no longer invalid](https://lux.postlight.com/docs/1.0/guide/route-definitions).

**Comment by Photon79** [comment]
@zacharygolba Thanks
