### ISSUE TITLE
'data' is not a valid parameter for this resource on POST to custom route

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#531]
When sending a POST request with a valid JSON API create request, an error (w/ a 400 Bad Request) is thrown from the route stating that 'data' is not a valid parameter.

Request:
```
POST http://localhost:5000/employees
{
  "data": {
    "type": "employees",
    "attributes": {
      "email": "mail@example.com",
      "first-name": "Nick",
      "sur-name": "Schot"
    }
  }
}
```

Stacktrace:
```
TypeError: 'data' is not a valid parameter for this resource.
    at Map.validate (/node_modules/lux-framework/src/packages/router/route/params/parameter-group/index.js:61:17)
    at /node_modules/lux-framework/src/packages/router/route/index.js:153:27
    at Generator.next (<anonymous>)
    at step (/dist/bundle.js:235:30)
    at /dist/bundle.js:253:14
    at /dist/bundle.js:232:12
    at Set.visit (/dist/bundle.js:8439:7)
    at parseRequest.then.params (/node_modules/lux-framework/src/packages/server/index.js:119:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by nickschot** [comment]
Fixed by adding 'data' to the query array.

`query` !== `query parameters` in the controller as @zacharygolba pointed out (thanks!).

**Comment by zacharygolba** [comment]
Should be noted that is only necessary for custom routes with model-less controllers.
