### ISSUE TITLE
Breaks when model name is the same as a class name in lux

### ISSUE THREAD

**Issue by seawatts** [postlight/lux#601]
I tried to create a model name `server` and there is a `Server` class already defined in lux. When the app gets compiled it renames the model to `server$2` and then when trying to insert new objects into the server table it throws an error 

```bash
Error: SQLITE_ERROR: no such table: server$2s
    at Client_SQLite3._query (./node_modules/knex/lib/dialects/sqlite3/index.js:138:12)
    at Client_SQLite3.query (./node_modules/knex/lib/client.js:189:17)
    at ./node_modules/knex/lib/transaction.js:263:21
From previous event:
    at Client_SQLite3.trxClient.query (./node_modules/knex/lib/transaction.js:260:34)
    at Runner.<anonymous> (./node_modules/knex/lib/runner.js:138:36)
From previous event:
    at ./node_modules/knex/lib/runner.js:61:21
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at Runner.run (./node_modules/knex/lib/runner.js:47:31)
    at Builder.Target.then (./node_modules/knex/lib/interface.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by zacharygolba** [comment]
[rollup-plugin-lux](https://github.com/postlight/rollup-plugin-lux) addresses this. It will be implemented in Lux core soon.
