### ISSUE TITLE
SyntaxError when serving in production mode

### ISSUE THREAD

**Issue by nickschot** [postlight/lux#618]
`SyntaxError: Comma is not permitted after the rest element (23:2500) in /node_modules/lux-framework/src/packages/database/query/index.js` when doing a `lux s -e production`.

Node v7.x.x
Lux v1.1.2

Relevant stack trace:
```sh
SyntaxError: Comma is not permitted after the rest element (23:2500) in /node_modules/lux-framework/src/packages/database/query/index.js
    at Parser.pp$4.raise (/node_modules/rollup/node_modules/acorn/src/location.js:15:13)
    at Parser.pp.checkPatternErrors (/node_modules/rollup/node_modules/acorn/src/parseutil.js:105:22)
    at Parser.pp$3.parseMaybeAssign (/node_modules/rollup/node_modules/acorn/src/expression.js:107:10)
    at Parser.pp$3.parseParenAndDistinguishExpression (/node_modules/rollup/node_modules/acorn/src/expression.js:392:28)
    at Parser.pp$3.parseExprAtom /node_modules/rollup/node_modules/acorn/src/expression.js:325:17)
    at Parser.pp$3.parseExprSubscripts (/node_modules/rollup/node_modules/acorn/src/expression.js:223:19)
    at Parser.pp$3.parseMaybeUnary (/node_modules/rollup/node_modules/acorn/src/expression.js:200:17)
    at Parser.pp$3.parseExprOp (/node_modules/rollup/node_modules/acorn/src/expression.js:163:41)
    at Parser.pp$3.parseExprOp (/node_modules/rollup/node_modules/acorn/src/expression.js:165:19)
    at Parser.pp$3.parseExprOps (/node_modules/rollup/node_modules/acorn/src/expression.js:146:15)
    at Parser.pp$3.parseMaybeConditional (/node_modules/rollup/node_modules/acorn/src/expression.js:127:19)
    at Parser.pp$3.parseMaybeAssign (/node_modules/rollup/node_modules/acorn/src/expression.js:104:19)
```

**Comment by zacharygolba** [comment]
This is likely a babel bug. Try `rm -rf node_modules && npm cache clean && npm i`. Also, using yarn may prevent this stuff from happening in the future.

**Comment by nickschot** [comment]
Unfortunately that doesn't fix the problem. Tried with both yarn 0.18.1 and npm 4.0.5. Could still be a babel bug of course.

**Comment by nickschot** [comment]
I am not encountering this anymore. Did get a different error, but that was related to my own code (it did only show up in production mode).
