### ISSUE TITLE
Something causes lux/knex to attempt using my username as database name instead of the configured value (with Postgresql)

### ISSUE THREAD

**Issue by havremunken** [postlight/lux#624]
As discussed in Gitter over the last few days, I have suddenly ran into an issue with database operations in lux 1.1.2. 

So far, I have identified that this happens when I try the operations db:create, db:reset and db:drop. `lux serve` however connects to the correct database according to the config/database.js. 

Here is my database config (these are all just temporary values on a box that won't be around much longer and the db isn't reachable from the outside, so actual values all the way.

```
export default {
  development: {
   driver: 'pg',
   username: 'troillprat',
   //host: 'localhost',
   database: 'troillprat_backend_dev',
   password: 'troillprat'
  },
  test: {
   driver: 'sqlite3',
   database: 'troillprat_backend_test'
  },
  production: {
   driver: 'pg',
   username: 'troillprat',
   host: 'localhost',
   database: 'troillprat_backend_dev',
   password: 'troillprat'
 }
};
```
(I tried commenting out the hostname for my development config to see if it made a difference, which it didn't)

When I run `lux serve` it functions as expected - data is fetched from the database and sent to the client in JSONAPI format. This also means that at some point this did work, or I wouldn't have a database schema.

Example of trying to run db:create:

```
rune@prat:~/src/troillprat/troillprat-backend$ lux db:create
error: database "rune" does not exist
    at Connection.parseE (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
From previous event:
    at Client_PG.acquireRawConnection (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/dialects/postgres/index.js:142:12)
    at Object.create (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/client.js:231:16)
    at Pool._createResource (/home/rune/src/troillprat/troillprat-backend/node_modules/generic-pool/lib/generic-pool.js:326:17)
    at Pool._ensureMinimum (/home/rune/src/troillprat/troillprat-backend/node_modules/generic-pool/lib/generic-pool.js:364:12)
    at new Pool (/home/rune/src/troillprat/troillprat-backend/node_modules/generic-pool/lib/generic-pool.js:156:8)
    at Client_PG.initializePool (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/client.js:261:17)
    at Client_PG.Client (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/client.js:108:12)
    at new Client_PG (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/dialects/postgres/index.js:56:20)
    at Knex (/home/rune/src/troillprat/troillprat-backend/node_modules/knex/lib/index.js:60:34)
    at connect (/home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/src/packages/database/utils/connect.js:54:3)
    at /home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/src/packages/cli/commands/dbcreate.js:34:24
    at next (native)
    at step (/home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/dist/dbcreate.js:86:30)
    at /home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/dist/dbcreate.js:104:14
    at /home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/dist/dbcreate.js:83:12
    at dbcreate (/home/rune/src/troillprat/troillprat-backend/node_modules/lux-framework/src/packages/cli/commands/dbcreate.js:12:1)
    at exec (/usr/lib/node_modules/lux-framework/bin/lux:88:18)
    at exec.then (/usr/lib/node_modules/lux-framework/bin/lux:205:19)
```

Not having the word "rune" anywhere in my database config, I can only conclude it is using my username. My "proof" for this is the following:

```
rune@prat:~/src/troillprat/troillprat-backend$ sudo lux db:create
[sudo] password for rune:
error: database "root" does not exist
    at Connection.parseE (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:554:11)
    at Connection.parseMessage (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:381:17)
    at Socket.<anonymous> (/home/rune/src/troillprat/troillprat-backend/node_modules/pg/lib/connection.js:117:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

As you can see, it now tries to connect to the "root" database, which also doesn't exist (and isn't referred to in the config).

I am even less familiar with knex than I am with lux, but if you need me to test anything, just let me know. Luckily `lux db:migrate` works so I can work around this, but it would be great to figure out why this happens.

On the server (Ubuntu 14.04) I have the following versions:

```
lux --version && node --version && npm --version
1.1.2
v6.9.4
3.10.10
```

On my dev box I have the same lux, but node 7.4.0 and npm 4.0.5 I believe.

**Comment by seawatts** [comment]
This should be fixed with https://github.com/postlight/lux/pull/605

**Comment by nickschot** [comment]
@seawatts he's already using 1.1.2 which contains #605 . I myself haven't encountered this specific problem.

**Comment by seawatts** [comment]
I'm actually still running into this on 1.1.5

**Comment by havremunken** [comment]
Same here, getting the problem on two different machines with 1.1.5, both of them running Ubuntu Linux 16.04.

For completeness, here are the operations that work (i.e. they don't try to use my username as the db name, and do what is expected of them:

lux db:migrate
lux db:rollback
lux db:seed

These ***do not*** work:

lux db:create
lux db:drop
lux db:reset

**Comment by zacharygolba** [comment]
Thanks for the info @seawatts, @havremunken. I'm going to do some debugging later and hopeful publish a patch with a fix soon.

**Comment by adriennn** [comment]
are we still seeing this? I had to load a library in my knexfile to be able to read from process.env
