### ISSUE TITLE
Error to start an application

### ISSUE THREAD

**Issue by newaeonweb** [postlight/lux#686]
*   **Platform**: Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64
*   **Database**: No database
*   **Lux Version**: Impossible to see, get error
*   **Node Version**: 4.2.2

/usr/local/lib/node_modules/lux-framework/bin/lux:5
const { EOL } = require('os');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

**Comment by zacharygolba** [comment]
Hi @newaeonweb thanks for reporting this issue!

It looks like you using Node `4.2.2`. Lux requires at least Node 6.

Let me know if you still are having issues after you upgrade your Node version. :)
